export default [
  {
    url: '/dashboard',
    name: 'Dashboard',
    icon_url: 'dashboard.png',
    i18n: 'Dashboard',
  },
  {
    url: '#',
    name: 'Users',
    icon_url: 'dashboard.png',
    i18n: 'Users',
  },
  {
    url: '#',
    name: 'Abis',
    icon_url: 'dashboard.png',
    i18n: 'Abis',
  },
  {
    url: '#',
    name: 'Partners',
    icon_url: 'dashboard.png',
    i18n: 'Partners',
  },
  {
    url: '#',
    name: 'Companies',
    icon_url: 'dashboard.png',
    i18n: 'Companies',
  },
  {
    url: '#',
    name: 'Operators',
    icon_url: 'dashboard.png',
    i18n: 'Operators',
  },
  {
    url: '#',
    name: 'Persons',
    icon_url: 'dashboard.png',
    i18n: 'Persons',
  },
  {
    url: '#',
    name: 'Infos',
    icon_url: 'plugins.png',
    i18n: 'Infos',
  },
  {
    url: '/document',
    name: 'Documents',
    icon_url: 'documents.png',
    i18n: 'Documents',
  },
  {
    url: '/template',
    name: 'Templates',
    icon_url: 'layers.png',
    i18n: 'Templates',
  },
  {
    url: '/flows',
    name: 'Flows',
    icon_url: 'flows.png',
    i18n: 'Flows',
  },
  {
    url: '/flows',
    name: 'Operations',
    icon_url: 'flows.png',
    i18n: 'Operations',
  },
  {
    url: '/notarizations',
    name: 'NotariZations',
    icon_url: 'notarization.png',
    i18n: 'NotariZations',
  },
  {
    url: '#',
    name: 'Seats',
    icon_url: 'dashboard.png',
    i18n: 'Seats',
  },
  {
    url: '#',
    name: 'Devices',
    icon_url: 'dashboard.png',
    i18n: 'Devices',
  },
  {
    url: '#',
    name: 'Licences',
    icon_url: 'dashboard.png',
    i18n: 'Licences',
  },
  {
    url: '#',
    name: 'Wallets',
    icon_url: 'plugins.png',
    i18n: 'Wallets',
  },
  {
    url: '#',
    name: 'Payments',
    icon_url: 'plugins.png',
    i18n: 'Payments',
  },
  {
    url: '#',
    name: 'Limits',
    icon_url: 'plugins.png',
    i18n: 'Limits',
  },
  {
    url: '#',
    name: 'Presets',
    icon_url: 'plugins.png',
    i18n: 'Presets',
  },
  {
    url: '#',
    name: 'Subscriptions',
    icon_url: 'plugins.png',
    i18n: 'Subscriptions',
  },
  {
    url: '#',
    name: 'Modules',
    icon_url: 'plugins.png',
    i18n: 'Modules',
  },
  {
    url: '#',
    name: 'CertiFicators',
    icon_url: 'plugins.png',
    i18n: 'CertiFicators',
  },
  {
    url: '#',
    name: 'Tasks',
    icon_url: 'identity.png',
    i18n: 'Tasks',
  },
  {
    url: '#',
    name: 'Notifications',
    icon_url: 'identity.png',
    i18n: 'Notifications',
  },
  {
    url: '#',
    name: 'Logs',
    icon_url: 'plugins.png',
    i18n: 'Logs',
  },

]
